### ISSUE TITLE
Cannot trigger action by "Enter" key in Narrator scan mode 

### ISSUE THREAD

**Issue by KeiraYang** [accessibilitysupported/a11ysupport.io#123] opened 2020-07-16 06:04 UTC
Hi,

I'm using Narrator scan mode to go through the items in the page and tried to activate the button. But I cannot trigger the action by "Enter" key. Narrator will read "Item has no primary action".

Instead, "Ctrl + Enter" works. I'm trying to understand what's wrong. Can someone help explain what is "Primary action" and "Secondary action" shows in the screenshot?

As I checked the event, the keydown event on that element never get triggered. But it works in Narrator scan off mode and without Narrator.  Any possible reason which caused the issue that I can dig more? Great thanks in advance!

![image](https://user-images.githubusercontent.com/28148759/87631121-4fa61780-c769-11ea-8350-8b91eece792f.png)

**Comment by mfairchild365** [comment] 2020-07-16 12:33
Hi @KeiraYang, thank you for posting this. A couple of questions.

1. Did you find this issue while testing something on a11ysupport.io? If so, can you link me to it?
2. If no, can you please share a code example where I can reproduce this problem?

**Comment by KeiraYang** [comment] 2020-07-20 16:48
Hi @mfairchild365. Sorry for the late response. I can repro the issue with below example:

`
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>runoob.com</title>
</head>
<body>
<button id="myBtn">Click me</button>
<p id="demo"></p>
<script>
	function displayDate(ev) {
		if (ev.which == 13 || ev.which == 32) {
			alert(Date());
		}
	};
		
	document.getElementById("myBtn").addEventListener("keydown", displayDate);
</script>

</body>
</html>
`

As I checked, in screen reader scan mode, the event cannot be triggered by Enter or space key. But other keys can, e.g. Ctrl, Shift etc if you remove the condition. Any idea on this?

**Comment by mitchellevan** [comment] 2020-07-20 20:19
The code sample is ambiguous because it does not include the #myBtn element
where the event is bound. The element type makes a difference in what to
recommend.

If you want the simplest code with robust button behavior, the best choice
is a click event on a <button> element.

The KeyboardEvent.which property is obsolete.

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which

**Comment by mfairchild365** [comment] 2020-07-20 20:44
As @mitchellevan suggested, using a `click` event listener will yield what you expect here. Using `keydown` while in scan mode is not expected to work.

Windows desktop screen readers offer a "browse" mode and "forms mode". Each screen reader calls them slightly different things.

- Browse mode (scan mode in Narrator): keypresses are intercepted by the screen reader to allow for shortcuts.
- Forms mode (scan mode off): keypresses bypass the screen-reader and are routed as normal to the application.

When pressing `enter` on a button while in scan mode, the screen reader tries to do you a solid and sends a synthetic `click` event. I'm not aware of a screen reader that also sends a `keydown` event in this situation (I quickly re-checked with NVDA and JAWS). 

I'll close this issue for now, but please comment / re-open if there is evidence that `keydown` should in fact be fired in this scenario.

**Closed by mfairchild365** 2020-07-20 20:44 UTC

**Comment by KeiraYang** [comment] 2020-07-27 10:57
Great thanks @mfairchild365 and @mitchellevan for helping. Add click event hanlder resolved my issue. I still have the question on the Narrator document for the primary action and secondary action mean:
![image](https://user-images.githubusercontent.com/28148759/88534523-d9dc5e80-d03a-11ea-9c47-f554778d5617.png)
Could you please help provide explaination on what the primary and secondary action means? Thanks in advance!

**Comment by mitchellevan** [comment] 2020-07-27 11:45
The primary action is activating the control, like a pointer click. Like
you @KeiraYang I'm also curious what a "secondary action" might be.

For folks who can't see KeiraYang's screen shot, it's the first four rows
of the first table in Narrator guide Chapter 3
<https://support.microsoft.com/en-us/help/22809>, starting with "Press
these keys / To do this".

-Mitchell

>
